const fs = require("fs");
const path = require("path");

const utm = require("utm");

const exportToTxt = (points, filename, projectName) => {
  if (!points || points.length === 0) {
    throw new Error("No points to export");
  }

  const totalPoints = points.length;
  const timestamp = new Date().toLocaleString();


  // Create header section with proper alignment
  const header = [
    `GEOnex Survey Export File`,
    `${'='.repeat(50)}`,
    `Generated At:    ${timestamp}`,
    `Project Name:    ${projectName}`,
    `Total Points:    ${totalPoints}`,
    `${'='.repeat(50)}`,
    ``
  ].join("\r\n");

  // Create column headers with proper spacing
  const columnHeaders = [
    `PointID`.padEnd(8) + 
    `Easting`.padEnd(15) + 
    `Northing`.padEnd(15) + 
    `Zone`.padEnd(8) + 
    `Description`,
    `${'-'.repeat(8)}${'-'.repeat(15)}${'-'.repeat(15)}${'-'.repeat(8)}${'-'.repeat(20)}`
  ].join("\n");

  // Create data rows with consistent spacing
  const dataRows = points.map((p, i) => {
    const pointId = (i + 1).toString();
    const description = p.Name || p.Type || "";

    let easting = "", northing = "", zone = "";
    if (p.Latitude != null && p.Longitude != null) {
      const utmCoord = utm.fromLatLon(p.Latitude, p.Longitude);
      easting = utmCoord.easting.toFixed(3);
      northing = utmCoord.northing.toFixed(3);
      zone = `${utmCoord.zoneNum}${utmCoord.zoneLetter}`;
    }

    return pointId.padEnd(8) + 
           easting.padEnd(15) + 
           northing.padEnd(15) + 
           zone.padEnd(8) + 
           description;
  }).join("\n");

  // Footer section
  const footer = [
    ``,
    `${'='.repeat(50)}`,
    `End of Export - ${totalPoints} points processed`,
    `Automatically Generated by GEOnex Survey System`,
    `${'='.repeat(50)}`
  ].join("\n");

  // Combine all sections
  const content = [header, columnHeaders, dataRows, footer].join("\n");
  
  // Ensure export directory exists
  const exportDir = path.join(__dirname, "../exports");
  if (!fs.existsSync(exportDir)) {
    fs.mkdirSync(exportDir, { recursive: true });
  }

  // Write file with proper encoding
  const filePath = path.join(exportDir, filename);
  fs.writeFileSync(filePath,content);

  // Log success
  console.log(`✅ TXT file exported successfully: ${filePath}`);
  
  return filePath;
};

module.exports = { exportToTxt };